create schema if not exists accident;

create table if not exists accident.notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  body text,
  severity text not null default 'info',
  created_at timestamptz not null default now()
);

alter table accident.notifications replica identity full;

insert into accident.notifications (title, body, severity)
values
  ('Bridge inspection complete', 'All lanes reopened after the scheduled inspection.', 'info'),
  ('Heavy rain advisory', 'Expect slower traffic and reduced visibility on the eastern ring road.', 'warning')
on conflict do nothing;
